// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/check": {
            "post": {
                "description": "Check wallet security and get nutrition score",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Check wallet security",
                "parameters": [
                    {
                        "description": "Wallet address to check",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wallet.CheckWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wallet.CheckWalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/payment/create-invoice": {
            "post": {
                "description": "Create a payment invoice for wallet check activation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Create payment invoice",
                "parameters": [
                    {
                        "description": "Payment details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.CreateInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment.CreateInvoiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/payment/webhook": {
            "post": {
                "description": "Handle payment notifications from Telegram",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Handle Telegram webhook",
                "parameters": [
                    {
                        "description": "Webhook data from Telegram",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payment.WebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payment.WebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the service is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.CheckResult": {
            "type": "object",
            "properties": {
                "check_name": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "raw_data": {},
                "risk_found": {
                    "type": "boolean"
                },
                "risk_level": {
                    "$ref": "#/definitions/entity.RiskLevel"
                },
                "score_penalty": {
                    "type": "number"
                }
            }
        },
        "entity.RiskLevel": {
            "type": "string",
            "enum": [
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL"
            ],
            "x-enum-varnames": [
                "RiskLevelLow",
                "RiskLevelMedium",
                "RiskLevelHigh",
                "RiskLevelCritical"
            ]
        },
        "payment.CreateInvoiceRequest": {
            "type": "object",
            "required": [
                "address",
                "guid"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x0000db5c8B030ae20308ac975898E09741e70000"
                },
                "guid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "payment.CreateInvoiceResponse": {
            "type": "object",
            "properties": {
                "order_url": {
                    "type": "string",
                    "example": "https://t.me/pay?hash=1234567890abcdef"
                }
            }
        },
        "payment.WebhookRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "object",
                    "properties": {
                        "chat": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "integer"
                                },
                                "type": {
                                    "type": "string"
                                }
                            }
                        },
                        "date": {
                            "type": "integer"
                        },
                        "from": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "integer"
                                }
                            }
                        },
                        "message_id": {
                            "type": "integer"
                        },
                        "pre_checkout_query": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                }
                            }
                        },
                        "successful_payment": {
                            "type": "object",
                            "properties": {
                                "currency": {
                                    "type": "string"
                                },
                                "invoice_payload": {
                                    "type": "string"
                                },
                                "provider_payment_charge_id": {
                                    "type": "string"
                                },
                                "telegram_payment_charge_id": {
                                    "type": "string"
                                },
                                "total_amount": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                },
                "update_id": {
                    "type": "integer"
                }
            }
        },
        "payment.WebhookResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "wallet.CheckWalletRequest": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x0000db5c8B030ae20308ac975898E09741e70000"
                },
                "guid": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "wallet.CheckWalletResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.CheckResult"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommendations": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Wallet Nutrition Score API",
	Description:      "API for checking wallet security and calculating nutrition score",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
